topic:
  image_topic: "/axis/image_raw/compressed"
  imu_topic: "/imu/angular_velocity"
  speed_feedback_topic: "/e100/speed_feedback"
  steer_feedback_topic: "/e100/steer_feedback"

  vis_topic: "/vis_result"
  points_topic: "/points3d"
  path_topic : "/rs_path"
  rear_hitch_pos_topic: "/hitch_pos"
  front_hitch_pixel_topic: "/hitch_pixel"

  speed_topic: "/speed_cmd"
  steer_topic: "/steer_cmd"

fisheye_params:
  intrinsic_matrix: [561.69608, 0.0, 944.62267, 0.0, 562.83000, 549.53336, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.02037, 0.00576, -0.003325, 0.0001055]
  rot_vec: [1.63145466, 1.58020883, -0.91721348]
  trans_vec: [0.04336624, 0.69452095, -0.28834708]

vehicle_params:
  r_wheel: 0.24
  hitch_height: 0.272
  front_hitch_length: 0.69
  trailer_length: 1.68
  trailer_width: 0.9
  rear_hitch_length: 0.5
  rear_height: 0.3
  rear_hitch_height: 0.25

yolov8_pose:
  trt_file: "/home/tongyao/tensorrt-alpha/data/yolov8-pose/best-384.trt"
  size_w: 640
  size_h: 384
  src_w: 1920
  src_h: 1080
  conf_thresh: 0.25
  iou_thresh: 0.7

kf_tracker:
  std_weight_position: 0.033
  std_weight_velocity: 0.004
  std_weight_mea_detect: 0.05
  std_weight_mea_LK: 0.1
  std_weight_mea_3D: 0.1
